export const LIST_MY_TRANSACTION_REQUEST = "LIST_MY_TRANSACTION_REQUEST";
export const LIST_MY_TRANSACTION_SUCCESS = "LIST_MY_TRANSACTION_SUCCESS";
export const LIST_MY_TRANSACTION_FAIL = "LIST_MY_TRANSACTION_FAIL";
export const LIST_MY_TRANSACTION_RESET = "LIST_MY_TRANSACTION_RESET";
